steps:
- name: 'gcr.io/gcp-runtimes/ubuntu_18_0_4'
  entrypoint: 'curl'
  args: ['https://google.com/']
logsBucket: 'gs://rtrentin-01_cloudbuild'
options:
  workerPool:
    'projects/rtrentin01/locations/us-east1/workerPools/vpc001-private-pool'

